CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "ApplicationTemplates" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "NumberOfReferences" integer NOT NULL DEFAULT 3,
    "IsObsolete" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_ApplicationTemplates" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(255) NOT NULL,
    "FirstName" character varying(255) NOT NULL,
    "LastName" character varying(255) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "IsAdmin" boolean NOT NULL DEFAULT FALSE,
    "IsSysAdmin" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_Users_Username" UNIQUE ("Username")
);

CREATE TABLE "ApplicationTemplateDegrees" (
    "ApplicationTemplateId" integer NOT NULL,
    "Index" integer NOT NULL,
    "Name" character varying(255) NOT NULL,
    CONSTRAINT "PK_ApplicationTemplateDegrees" PRIMARY KEY ("ApplicationTemplateId", "Index"),
    CONSTRAINT "FK_ApplicationTemplateDegrees_ApplicationTemplates_Application~" FOREIGN KEY ("ApplicationTemplateId") REFERENCES "ApplicationTemplates" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ApplicationTemplateDocuments" (
    "ApplicationTemplateId" integer NOT NULL,
    "Index" integer NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Description" text NULL,
    CONSTRAINT "PK_ApplicationTemplateDocuments" PRIMARY KEY ("ApplicationTemplateId", "Index"),
    CONSTRAINT "FK_ApplicationTemplateDocuments_ApplicationTemplates_Applicati~" FOREIGN KEY ("ApplicationTemplateId") REFERENCES "ApplicationTemplates" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Departments" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "ChairId" integer NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Departments_Users_ChairId" FOREIGN KEY ("ChairId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Files" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "ContentType" character varying(255) NULL,
    "Timestamp" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "OwnerId" integer NOT NULL,
    "Content" bytea NULL,
    CONSTRAINT "PK_Files" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Files_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Searches" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DepartmentId" integer NOT NULL,
    "Position" character varying(255) NOT NULL,
    "StartDate" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "CloseDate" timestamp without time zone NULL,
    "DepartmentChairId" integer NOT NULL,
    "CommitteeChairId" integer NOT NULL,
    "ApplicationTemplateId" integer NOT NULL,
    CONSTRAINT "PK_Searches" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Searches_ApplicationTemplates_ApplicationTemplateId" FOREIGN KEY ("ApplicationTemplateId") REFERENCES "ApplicationTemplates" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Searches_Users_CommitteeChairId" FOREIGN KEY ("CommitteeChairId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Searches_Users_DepartmentChairId" FOREIGN KEY ("DepartmentChairId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Searches_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Applications" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "SearchId" integer NOT NULL,
    "FirstName" character varying(255) NOT NULL,
    "LastName" character varying(255) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "CurrentPosition" character varying(255) NULL,
    "CurrentEmployer" character varying(255) NULL,
    "IsWithdrawn" boolean NOT NULL DEFAULT FALSE,
    "IsDisqualified" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_Applications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Applications_Searches_SearchId" FOREIGN KEY ("SearchId") REFERENCES "Searches" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CommitteeMembers" (
    "SearchId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_CommitteeMembers" PRIMARY KEY ("SearchId", "UserId"),
    CONSTRAINT "FK_CommitteeMembers_Searches_SearchId" FOREIGN KEY ("SearchId") REFERENCES "Searches" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CommitteeMembers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ApplicationDegrees" (
    "ApplicationId" integer NOT NULL,
    "Index" integer NOT NULL,
    "Degree" character varying(255) NOT NULL,
    "Major" character varying(255) NOT NULL,
    "Institution" character varying(255) NOT NULL,
    "Year" integer NOT NULL,
    "IsExpected" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_ApplicationDegrees" PRIMARY KEY ("ApplicationId", "Index"),
    CONSTRAINT "FK_ApplicationDegrees_Applications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES "Applications" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ApplicationDocuments" (
    "ApplicationId" integer NOT NULL,
    "Index" integer NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Description" text NULL,
    "FileId" integer NULL,
    CONSTRAINT "PK_ApplicationDocuments" PRIMARY KEY ("ApplicationId", "Index"),
    CONSTRAINT "FK_ApplicationDocuments_Applications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES "Applications" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ApplicationDocuments_Files_FileId" FOREIGN KEY ("FileId") REFERENCES "Files" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ApplicationReferences" (
    "ApplicationId" integer NOT NULL,
    "Index" integer NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Institution" character varying(255) NOT NULL,
    "Title" character varying(255) NOT NULL,
    "Phone" character varying(255) NOT NULL,
    "ReportId" integer NULL,
    CONSTRAINT "PK_ApplicationReferences" PRIMARY KEY ("ApplicationId", "Index"),
    CONSTRAINT "FK_ApplicationReferences_Applications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES "Applications" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ApplicationReferences_Files_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Files" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Evaluations" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ApplicationId" integer NOT NULL,
    "EvaluatorId" integer NULL,
    "HaveMinimumQualifications" boolean NULL,
    "HavePreferredQualifications" boolean NULL,
    "IsAdvancedToPhoneInterview" boolean NULL,
    "IsAdvancedToCampusInterview" boolean NULL,
    "Notes" text NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Evaluations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Evaluations_Applications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES "Applications" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Evaluations_Users_EvaluatorId" FOREIGN KEY ("EvaluatorId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Revisions" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DocumentId" integer NOT NULL,
    "Number" integer NOT NULL,
    "AuthorId" integer NOT NULL,
    "FileId" integer NOT NULL,
    "Notes" text NULL,
    "Timestamp" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_Revisions" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_Revisions_DocumentId_Number" UNIQUE ("DocumentId", "Number"),
    CONSTRAINT "FK_Revisions_Users_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Revisions_Files_FileId" FOREIGN KEY ("FileId") REFERENCES "Files" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Documents" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "SearchId" integer NOT NULL,
    "Name" character varying(255) NOT NULL,
    "LatestRevisionId" integer NULL,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Documents_Revisions_LatestRevisionId" FOREIGN KEY ("LatestRevisionId") REFERENCES "Revisions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Documents_Searches_SearchId" FOREIGN KEY ("SearchId") REFERENCES "Searches" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ApplicationDocuments_FileId" ON "ApplicationDocuments" ("FileId");

CREATE INDEX "IX_ApplicationReferences_ReportId" ON "ApplicationReferences" ("ReportId");

CREATE INDEX "IX_Applications_SearchId" ON "Applications" ("SearchId");

CREATE INDEX "IX_CommitteeMembers_UserId" ON "CommitteeMembers" ("UserId");

CREATE INDEX "IX_Departments_ChairId" ON "Departments" ("ChairId");

CREATE INDEX "IX_Documents_LatestRevisionId" ON "Documents" ("LatestRevisionId");

CREATE INDEX "IX_Documents_SearchId" ON "Documents" ("SearchId");

CREATE INDEX "IX_Evaluations_EvaluatorId" ON "Evaluations" ("EvaluatorId");

CREATE UNIQUE INDEX "IX_Evaluations_ApplicationId_EvaluatorId" ON "Evaluations" ("ApplicationId", "EvaluatorId");

CREATE INDEX "IX_Files_OwnerId" ON "Files" ("OwnerId");

CREATE INDEX "IX_Revisions_AuthorId" ON "Revisions" ("AuthorId");

CREATE INDEX "IX_Revisions_FileId" ON "Revisions" ("FileId");

CREATE INDEX "IX_Searches_ApplicationTemplateId" ON "Searches" ("ApplicationTemplateId");

CREATE INDEX "IX_Searches_CommitteeChairId" ON "Searches" ("CommitteeChairId");

CREATE INDEX "IX_Searches_DepartmentChairId" ON "Searches" ("DepartmentChairId");

CREATE INDEX "IX_Searches_DepartmentId" ON "Searches" ("DepartmentId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

ALTER TABLE "Revisions" ADD CONSTRAINT "FK_Revisions_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20190930043042_InitialSchema', '3.0.0');

