ALTER TABLE "Searches" RENAME COLUMN "StartDate" TO "SearchStartDate";
ALTER TABLE "Searches" RENAME COLUMN "CloseDate" TO "SearchCloseDate";

ALTER TABLE "Searches" ADD COLUMN "ReviewStartDate" timestamp without time zone NULL;
ALTER TABLE "Searches" ADD COLUMN "PhoneInterviewStartDate" timestamp without time zone NULL;
ALTER TABLE "Searches" ADD COLUMN "CampusInterviewStartDate" timestamp without time zone NULL;

CREATE TABLE "Evaluations" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ApplicationId" integer NOT NULL,
    "EvaluatorId" integer NOT NULL,
    "Rating" integer NULL,
    "Notes" text NULL,
    CONSTRAINT "PK_Evaluations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Evaluations_Applications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES "Applications" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Evaluations_Users_EvaluatorId" FOREIGN KEY ("EvaluatorId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

ALTER SEQUENCE "Evaluations_Id_seq" RESTART WITH 1000000;

CREATE INDEX "IX_Evaluations_ApplicationId" ON "Evaluations" ("ApplicationId");

CREATE INDEX "IX_Evaluations_EvaluatorId" ON "Evaluations" ("EvaluatorId");

UPDATE "__EFMigrationsHistory" set "MigrationId" = '20191212010941_InitialSchema', "ProductVersion" = '3.1.0';
